import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import * as nodemailer from 'nodemailer';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class EmailService {
  private transporter: nodemailer.Transporter;

  constructor(private prisma: PrismaService) {
    this.transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.ethereal.email',
      port: Number(process.env.SMTP_PORT) || 587,
      auth: {
        user: process.env.SMTP_USER || 'ethereal.user@ethereal.email',
        pass: process.env.SMTP_PASS || 'ethereal-pass',
      },
    });
  }

  async sendProposalEmail(tenantId: string, leadId: string) {
    const lead: any = await this.prisma.lead.findFirst({
      where: { id: leadId, tenantId },
      include: {
        proposals: {
          orderBy: { createdAt: 'desc' }
        },
      } as any,
    });

    if (!lead) {
      throw new NotFoundException(`Lead not found`);
    }

    if (!lead.email) {
      throw new BadRequestException(`Lead ${lead.name} does not have an email address`);
    }

    const proposal = lead.proposals[0];
    if (!proposal) {
      throw new BadRequestException(`Lead ${lead.name} does not have an associated proposal. Please generate one first.`);
    }

    const info = await this.transporter.sendMail({
      from: '"Ai Saas CRM" <no-reply@aisaascrm.com>',
      to: lead.email,
      subject: `Proposal: ${proposal.title} - ${lead.company}`,
      text: `Dear ${lead.name},\n\nPlease find your security proposal details below:\n\n${proposal.content}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
          <h2 style="color: #4f46e5;">Your Security Proposal</h2>
          <p>Dear ${lead.name},</p>
          <p>Thank you for choosing <strong>Ai Saas CRM</strong>. We have generated a professional security proposal for <strong>${lead.company}</strong>.</p>
          <div style="background-color: #f9fafb; padding: 20px; border-radius: 12px; border: 1px solid #e5e7eb; margin: 20px 0;">
            <h3 style="margin-top: 0; color: #111827;">${proposal.title}</h3>
            <div style="white-space: pre-wrap; font-size: 14px; line-height: 1.6; color: #4b5563;">
              ${proposal.content.replace(/\n/g, '<br/>')}
            </div>
          </div>
          <p style="font-size: 12px; color: #9ca3af; margin-top: 30px;">
            This email was automatically generated by your AI Saas CRM.
          </p>
        </div>
      `,
    });

    // Update proposal status to 'sent'
    await (this.prisma as any).proposal.update({
      where: { id: proposal.id },
      data: { status: 'sent' }
    });

    return { 
      messageId: info.messageId, 
      previewUrl: nodemailer.getTestMessageUrl(info),
      status: 'sent'
    };
  }

  async sendBulkProposalEmails(tenantId: string) {
    const leads: any[] = await this.prisma.lead.findMany({
      where: { 
        tenantId,
        email: { not: null } as any,
        proposals: { some: {} } as any
      } as any,
      include: { 
        proposals: {
          orderBy: { createdAt: 'desc' }
        } 
      } as any
    });

    let sentCount = 0;
    let skippedMissingEmail = 0;
    let skippedMissingProposal = 0;
    const results: any[] = [];

    // Fetch all leads for the tenant to diagnose
    const allLeads: any[] = await this.prisma.lead.findMany({
      where: { tenantId },
      include: { proposals: true } as any
    });

    for (const lead of allLeads) {
      if (!lead.email) {
        skippedMissingEmail++;
        continue;
      }
      if (!lead.proposals || lead.proposals.length === 0) {
        skippedMissingProposal++;
        continue;
      }

      try {
        const proposal = lead.proposals[0];
        const info = await this.transporter.sendMail({
          from: '"Ai Saas CRM" <no-reply@aisaascrm.com>',
          to: lead.email,
          subject: `Proposal: ${proposal.title} - ${lead.company}`,
          html: `
            <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
              <h2 style="color: #4f46e5;">Your Security Proposal</h2>
              <p>Dear ${lead.name},</p>
              <div style="background-color: #f9fafb; padding: 20px; border-radius: 12px; border: 1px solid #e5e7eb; margin: 20px 0;">
                <h3 style="margin-top: 0; color: #111827;">${proposal.title}</h3>
                <p>${proposal.content.replace(/\n/g, '<br/>')}</p>
              </div>
            </div>
          `,
        });
        
        await (this.prisma as any).proposal.update({
          where: { id: proposal.id },
          data: { status: 'sent' }
        });

        sentCount++;
        results.push({ leadId: lead.id, previewUrl: nodemailer.getTestMessageUrl(info) });
      } catch (error) {
        console.error(`Failed to send email to lead ${lead.id}`, error);
      }
    }

    return { 
      sentCount, 
      totalLeads: allLeads.length, 
      skippedMissingEmail, 
      skippedMissingProposal,
      results 
    };
  }
}
